repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: check-docstring-first
    -   id: detect-private-key
    -   id: requirements-txt-fixer
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
##### PYTHON #####
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.0.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        exclude: ^deploy/backend/app/routes/
- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v3.0.0a5
  hooks:
    - id: pylint
      args: [--disable=all, --enable=unused-import]
##### TERRAFORM #####
- repo: https://github.com/terraform-docs/terraform-docs
  rev: "v0.16.0"
  hooks:
    - id: terraform-docs-go
      args: ["markdown", "table", "--output-file", "README.md", "./"]
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: "v1.74.1"
  hooks:
    - id: terraform_fmt
    - id: terraform_tflint
    - id: terraform_validate
