repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-docstring-first
    -   id: detect-private-key
    -   id: requirements-txt-fixer
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
##### PYTHON #####
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: [--config=deploy/backend/python-app/setup.cfg]
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.0.0'
    hooks:
    -   id: mypy
        name: mypy_1
        files: deploy/frontend/python-app
    -   id: mypy
        name: mypy_2
        files: deploy/backend/python-app/
        exclude: ^deploy/backend/python-app/app/routes/

- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v3.0.0a5
  hooks:
    - id: pylint
      args: [--disable=all, --enable=unused-import]
##### TERRAFORM #####
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: 'v1.74.1'
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
#    - id: terrascan
