apiVersion: v1
kind: Service
metadata:
  name: cnk-service
spec:
  selector:
    app: cnk
  ports:
  - name: http-frontend
    port: 5000
    targetPort: 5000
  - name: http-backend
    port: 8000
    targetPort: 80
  type: LoadBalancer
