site_name: ckn backend service
site_dir: public
site_url: https://yuyatinnefeld.github.io/cloud-native-kiosk
repo_url: https://github.com/yuyatinnefeld/cloud-native-kiosk
theme:
    name: material
    palette:
      primary: teal

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences

strict: false

plugins:
  - gen-files:
      scripts:
        - docs/gen_mkdocs_pages.py
  - mkdocstrings:
      handlers:
        python:
          paths: [app]
          rendering:
            show_root_heading: true
            show_signature_annotations: true
            show_source: false
          rendering:
            show_root_heading: false
