name: 🚀ALERTING SERVICE🚀
run-name: Publish GCP Alerting Service
on: [push]

env:
  ENV: DEV
  TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}


jobs:
  gcp-application:
    name: 'Provisioning GCP Application'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./deploy/alerting

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: ${{ secrets.GCP_SERVICE_KEY }}

    - name: Unit Test
      run: echo "Run Unit Tests"

    - name: Deploy GCP Cloud Run
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: 'alerting-cloud-run'
        image: 'eu.gcr.io/${GCP_PROJECT_ID}/cnk-alerting:1.0.0'

    - name: Integration Test
      run: echo "Call the GCP Service"
