name: 🚀ALERTING SERVICE🚀
run-name: Publish GCP Alerting Service
on: [push]

env:
  ENV: DEV
  TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: europe-west1


jobs:
  gcp-application:
    name: 'Provisioning GCP Application'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./deploy/alerting

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: 'actions/checkout@v3'

    - name: Auth via Credentials json
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_KEY }}'

    - name: Unit Test
      run: echo "Run Unit Tests"

    - name: Deploy Application
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: 'alerting-cloud-run'
        image: 'eu.gcr.io/${{ env.GCP_PROJECT_ID }}/cnk-alerting:1.0.0'
        platform: managed
        region: ${{ env.REGION }}
        memory: 512Mi
        min-instances: 1
        max-instances: 2
        update-env-vars: ENV=${{ env.ENV }}
        update-secrets: -secrets=webhook_url_teams_error=webhook_url_teams_error:latest,webhook_url_slack_error=webhook_url_slack_error:latest

    - name: Integration Test
      run: echo "Call the GCP Application"
