name: 📄Documentation BE📄
on:
  # trigger the action after the python ci tests
  workflow_run:
    workflows: ["🧪Python CI BE Test🧪"]
    branches: [develop]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Generate Doc and Publish
        working-directory: ./deploy/backend
        run: |
          pip install mkdocs-material jinja2==3.0.0 Markdown==3.3.6 mkdocs==1.2.3 mkdocs-autorefs==0.4.1 mkdocs-gen-files==0.3.3 mkdocs-material-extensions==1.0.3 mkdocstrings==0.19.0 mkdocstrings-python==0.7.1
          mkdocs gh-deploy --force
