name: 📄Documentation BE📄
on:
  # trigger the action after the python ci tests
  workflow_run:
    workflows: ["🧪Python CI BE Test🧪"]
    branches: [develop]
    types:
      - completed

defaults:
  run:
    shell: bash
    working-directory: ./deploy/backend/python-app
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: pip install -r dev-requirements.txt -e .
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: mkdocs build --site-dir public
      - run: mkdocs gh-deploy --force