name: 🧪Python CI FE Test🧪

on: [push, pull_request]

defaults:
  run:
    shell: bash
    working-directory: ./deploy/frontend/python-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev

    - name: Run PyTest tests
      run: |
        pipenv run pip install Flask==2.2.2 Flask-Login==0.6.2 pytest==7.2.1
        pipenv run python -m pytest tests

    - name: Run Flake8 linting
      run: |
        pipenv run pip install flake8
        pipenv run flake8 app

    - name: Run security checks
      run: |
        pipenv run pip install safety
        pipenv run safety check -r requirements.txt

    - name: Run dependency checks
      run: |
        pipenv check
