name: Python Package CI Test for Frontend Service

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv 
        pipenv install --dev
        pip install Flask==2.2.2
        cd ./deploy/frontend/app/

    - name: Run PyTest tests
      run: |
        pipenv run python -m pytest

    - name: Run Flake8 linting
      run: |
        pipenv run pip install flake8
        pipenv run flake8 .

    - name: Run security checks
      run: |
        pipenv run pip install safety
        pipenv run safety check

    - name: Run dependency checks
      run: |
        pipenv check
